# Generated by Django 3.2.9 on 2021-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feed_date',
            field=models.DateField(),
        ),
    ]
