# Generated by Django 3.2.9 on 2021-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_user_feed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='image',
            new_name='image_src',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feed_date',
        ),
        migrations.AddField(
            model_name='headline',
            name='channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
