# Generated by Django 3.2.9 on 2021-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_paper',
            field=models.TextField(),
        ),
    ]
