# Generated by Django 3.2.9 on 2021-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211203_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='channel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='headline',
            name='source',
            field=models.URLField(),
        ),
    ]
